name: flutter_tappay_sdk_example
description: 'Demonstrates how to use the flutter_tappay_sdk plugin.'

publish_to: 'none'
version: 1.0.0+0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_tappay_sdk:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
