name: flutter_tappay_sdk
description: 'A Flutter plugin for TapPay SDK.'
version: 0.0.1

environment:
  sdk: '>=3.2.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: kent.chien.flutter_tappay_sdk
        pluginClass: FlutterTapPaySdkPlugin
      ios:
        pluginClass: FlutterTapPaySdkPlugin
