name: flutter_tappay_sdk
description: 'This project is a Flutter SDK for TapPay, a popular payment gateway from Taiwan.'
version: 0.2.0
homepage: https://github.com/Kent1011/flutter_tappay_sdk

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: kent.chien.flutter_tappay_sdk
        pluginClass: FlutterTapPaySdkPlugin
      ios:
        pluginClass: FlutterTapPaySdkPlugin
